FROM bigscience/biodesktop:ubuntu



RUN apt-get update
RUN apt-get install graphviz -y

RUN wget https://bitbucket.org/taverna/taverna-workbench-product/downloads/taverna-workbench-bioinformatics-2.5.0-standalone.zip
RUN wget http://download.oracle.com/otn-pub/java/jce/7/UnlimitedJCEPolicyJDK7.zip
